Controllers/LoginController.cs
using Meeting_room_dating.ViewModels;
using Meeting_room_dating.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meeting_room_dating.Controllers
{
    public class LoginController : Controller
    {
        UserService _service = new UserService();

        // GET: Login
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 確認使用者是否存在
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult LoginCheck(UserViewModel model)
        {
            try
            {
                var UserData = _service.LoginCheck(model);

                return Json(UserData);
            }
            catch (Exception ex)
            {
                return Json(new User());
            }
        }
    }
}

Controllers/MeetingRoomLogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meeting_room_dating.Controllers
{
    public class MeetingRoomLogController : Controller
    {
        // GET: MeetingRoomLog
        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/RoomReservationController.cs
using Meeting_room_dating.ViewModels;
using Meeting_room_dating.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meeting_room_dating.Controllers
{
    public class RoomReservationController : Controller
    {
        ReservationService _service = new ReservationService();

        // GET: RoomReservation
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 新增預約
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult InsertObj(Reservation model)
        {
            try
            {
                var isOK = _service.AddOrUpdateObj(model);

                return Json(isOK);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        /// <summary>
        /// 確認預約是否衝突到其他預約
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult CheckObjStatus(ReservationViewModel model)
        {
            try
            {
                var checkStatus = _service.CheckObjConflict(model);

                return Json(checkStatus);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

Controllers/UserRegitrationController.cs
using Meeting_room_dating.ViewModels;
using Meeting_room_dating.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meeting_room_dating.Controllers
{
    public class UserRegitrationController : Controller
    {
        UserService _service = new UserService();

        // GET: UserRegitration
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 新增使用者
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult InsertObj(User model)
        {
            try
            {
                var isOK = _service.AddOrUpdateObj(model);

                return Json(isOK);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        /// <summary>
        /// 確認使用者是否存在
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult CheckObjStatus(UserViewModel model)
        {
            try
            {
                var checkStatus = _service.CheckObjStatus(model);

                return Json(checkStatus);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="zh_tw">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link href="~/Content/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">
    <link href="~/Content/assets/vendor/fonts/circular-std/style.css" rel="stylesheet">
    <link href="~/Content/assets/libs/css/style.css"rel="stylesheet">
    <link href="~/Content/assets/vendor/fonts/fontawesome/css/fontawesome-all.css"rel="stylesheet">
    <link href="~/Content/assets/vendor/charts/chartist-bundle/chartist.css"rel="stylesheet">
    <link href="~/Content/assets/vendor/charts/morris-bundle/morris.css"rel="stylesheet">
    <link href="~/Content/assets/vendor/fonts/material-design-iconic-font/css/materialdesignicons.min.css"rel="stylesheet">
    <link href="~/Content/assets/vendor/charts/c3charts/c3.css"rel="stylesheet">
    <link href="~/Content/assets/vendor/fonts/flag-icon-css/flag-icon.min.css"rel="stylesheet">
    <title>約會(議室)系統</title>
</head>
<body>
    <!-- top navigation -->
    <div class="dashboard-header">
        @Html.Partial("_NavBar")
    </div>
    <!-- /top navigation -->
    <!-- sidebar menu -->
    <div class="nav-left-sidebar sidebar-dark">
        <div class="menu-list">
            @Html.Partial("_SideBar")
        </div>
    </div>
    <!-- /sidebar menu -->
    <!-- wrapper  -->
    <div class="dashboard-wrapper">
        <div class="container-fluid  dashboard-content">
            @RenderBody()
        </div>
    </div>
    <!-- /wrapper  -->
    <!-- Optional JavaScript -->
    <!-- jquery 3.3.1 -->
    <script src="~/Content/assets/vendor/jquery/jquery-3.3.1.min.js"></script>
    <!-- bootstap bundle js -->
    <script src="~/Content/assets/vendor/bootstrap/js/bootstrap.bundle.js"></script>
    <!-- slimscroll js -->
    <script src="~/Content/assets/vendor/slimscroll/jquery.slimscroll.js"></script>
    <!-- main js -->
    <script src="~/Content/assets/libs/js/main-js.js"></script>
    <!-- chart chartist js -->
    <script src="~/Content/assets/vendor/charts/chartist-bundle/chartist.min.js"></script>
    <!-- sparkline js -->
    <script src="~/Content/assets/vendor/charts/sparkline/jquery.sparkline.js"></script>
    <!-- morris js -->
    @*<script src="~/Content/assets/vendor/charts/morris-bundle/raphael.min.js"></script>
    <script src="~/Content/assets/vendor/charts/morris-bundle/morris.js"></script>*@
    <!-- chart c3 js -->
    @*<script src="~/Content/assets/vendor/charts/c3charts/c3.min.js"></script>
    <script src="~/Content/assets/vendor/charts/c3charts/d3-5.4.0.min.js"></script>
    <script src="~/Content/assets/vendor/charts/c3charts/C3chartjs.js"></script>
    <script src="~/Content/assets/libs/js/dashboard-ecommerce.js"></script>*@
    <!-- datepicker JavaScript -->
    <script src="~/Content/assets/vendor/datepicker/moment.js"></script>
    <script src="~/Content/assets/vendor/datepicker/tempusdominus-bootstrap-4.js"></script>
    <script src="~/Content/assets/vendor/datepicker/datepicker.js"></script>
    @RenderSection("scripts", required: false)
</body>
</html>

Views/Shared/_NavBar.cshtml
<nav class="navbar navbar-expand-lg bg-white fixed-top">
    <a class="navbar-brand" href="@Url.Action("Index","Home")">約會(議室)系統</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse " id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto navbar-right-top">
            <li class="nav-item dropdown nav-user">
                <a class="nav-link nav-user-img" href="#" id="navbarDropdownMenuLink2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"><img src="assets/images/avatar-1.jpg" alt="" class="user-avatar-md rounded-circle"></a>
                <div class="dropdown-menu dropdown-menu-right nav-user-dropdown" aria-labelledby="navbarDropdownMenuLink2">
                    <div class="nav-user-info">
                        <h5 id="NavUserName" class="mb-0 text-white nav-user-name">#使用者名稱：???</h5>
                        <span id="NavIdentity" class="ml-2">#身分：???</span>
                        <span id="NavUserID" class="hidden"></span>
                    </div>
                    <a class="dropdown-item" href="#"><i class="fas fa-user mr-2"></i>帳號狀況</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-cog mr-2"></i>Setting</a>
                    <a class="dropdown-item" href="#"><i class="fas fa-power-off mr-2"></i>登出</a>
                </div>
            </li>
        </ul>
    </div>
</nav>

Views/Shared/_SideBar.cshtml
<nav class='navbar navbar-expand-lg navbar-light'>
    <a class='d-xl-none d-lg-none' href='#'>Dashboard</a>
    <button class='navbar-toggler' type='button' data-toggle='collapse' data-target='#navbarNav' aria-controls='navbarNav' aria-expanded='false' aria-label='Toggle navigation'>
        <span class='navbar-toggler-icon'></span>
    </button>
    <div class='collapse navbar-collapse' id='navbarNav'>
        <ul class='navbar-nav flex-column'>
            <li class='nav-divider'>
                選單
            </li>
            <li class='nav-item '>
                <a class='nav-link' href='#' data-toggle='collapse' aria-expanded='false' data-target='#submenu-1' aria-controls='submenu-1'><i class='fa-fw fas fa-address-book'></i>帳號管理</a>
                <div id='submenu-1' class='collapse submenu' style=''>
                    <ul class='nav flex-column'>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","UserRegitration")'>帳號註冊</a>
                        </li>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","Login")'>登入</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class='nav-item'>
                <a class='nav-link' href='#' data-toggle='collapse' aria-expanded='false' data-target='#submenu-2' aria-controls='submenu-2'><i class='fa-fw fas fa-paste'></i>會議室</a>
                <div id='submenu-2' class='collapse submenu' style=''>
                    <ul class='nav flex-column'>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","MeetingRoomIntrodution")'>會議室介紹</a>
                        </li>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","MeetingRoomLog")'>會議室狀態列表</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class='nav-item'>
                <a class='nav-link' href='#' data-toggle='collapse' aria-expanded='false' data-target='#submenu-3' aria-controls='submenu-3'><i class='fa-fw fas fa-calendar-alt'></i>預約管理</a>
                <div id='submenu-3' class='collapse submenu' style=''>
                    <ul class='nav flex-column'>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","RoomReservation")'>預約登記</a>
                        </li>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","RoomReservationLog")'>預約查詢</a>
                        </li>
                    </ul>
                </div>
            </li>
            <li class='nav-item '>
                <a class='nav-link' href='#' data-toggle='collapse' aria-expanded='false' data-target='#submenu-4' aria-controls='submenu-4'><i class='fa-fw fas fa-cogs'></i>後台管理</a>
                <div id='submenu-4' class='collapse submenu' style=''>
                    <ul class='nav flex-column'>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","AccountManagement")'>帳號權限管理</a>
                        </li>
                        <li class='nav-item'>
                            <a class='nav-link' href='@Url.Action("Index","MeetingRoomManagement")'>會議室資訊編輯</a>
                        </li>
                    </ul>
                </div>
            </li>
        </ul>
    </div>
</nav>