Controllers/RoomReservationController.cs
using Meeting_room_dating.ViewModels;
using Meeting_room_dating.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meeting_room_dating.Controllers
{
    public class RoomReservationController : Controller
    {
        ReservationService _service = new ReservationService();

        // GET: RoomReservation
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 新增預約
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult InsertObj(Reservation model)
        {
            try
            {
                var isOK = _service.AddOrUpdateObj(model);

                return Json(isOK);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        /// <summary>
        /// 確認預約是否衝突到其他預約
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult CheckObjStatus(ReservationViewModel model)
        {
            try
            {
                var checkStatus = _service.CheckObjConflict(model);

                return Json(checkStatus);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

Controllers/RoomReservationLogController.cs
using Meeting_room_dating.ViewModels;
using Meeting_room_dating.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Meeting_room_dating.Controllers
{
    public class RoomReservationLogController : Controller
    {
        ReservationService _service = new ReservationService();

        // GET: RoomReservationLog
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 預約主表清單
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public PartialViewResult ObjListPartialView(ReservationViewModel model)
        {
            try
            {
                var objList = _service.SearchObjList(model);

                return PartialView(objList);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        /// <summary>
        /// 修改預約畫面
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public PartialViewResult UpdateObjPartialView(ReservationViewModel model)
        {
            try
            {
                model.StartTime = model.StartTime.ToUniversalTime();
                model.EndTime = model.EndTime.ToUniversalTime();
                var obj = _service.SearchObj(model);

                return PartialView(obj);
            }
            catch (Exception ex)
            {
                return null;
            }
        }

        /// <summary>
        /// 更改預約
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult InsertObj(Reservation model)
        {
            try
            {
                var isOK = _service.AddOrUpdateObj(model);

                return Json(isOK);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        /// <summary>
        /// 刪除預約
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult DeleteObj(ReservationViewModel model)
        {
            try
            {
                var isOK = _service.DeleteObj(model);

                return Json(isOK);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }

        /// <summary>
        /// 確認預約是否存在
        /// </summary>
        /// <param name="model"></param>
        /// <returns></returns>
        public JsonResult CheckObjExist(ReservationViewModel model)
        {
            try
            {
                var isExist = _service.CheckObjExist(model);

                return Json(isExist);
            }
            catch (Exception ex)
            {
                return Json(false);
            }
        }
    }
}

Views/RoomReservationLog/Index.cshtml
<!-- pageheader  -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="page-header">
            <h3 class="mb-2">預約查詢</h3>
            <div class="page-breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html" class="breadcrumb-link">首頁</a></li>
                        <li class="breadcrumb-item"><a href="index.html" class="breadcrumb-link">預約管理</a></li>
                        <li class="breadcrumb-item active" aria-current="page">預約查詢</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- /pageheader  -->
<!-- content  -->
<!-- influencer profile  -->
<div class="row">
    <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
        <div class="card influencer-profile-data">
            <div class="card-body">
                <div class="row">
                    <div class="col-xl-2 col-lg-4 col-md-4 col-sm-4 col-12">
                        <div class="text-center">
                            <img src="assets/images/avatar-1.jpg" alt="User Avatar" class="rounded-circle user-avatar-xxl">
                        </div>
                    </div>
                    <div class="col-xl-10 col-lg-8 col-md-8 col-sm-8 col-12">
                        <div class="user-avatar-info">
                            <div class="m-b-20">
                                <div class="user-avatar-name">
                                    <h2 class="mb-1">王曉明</h2>
                                </div>
                            </div>
                            <!--  <div class="float-right"><a href="#" class="user-avatar-email text-secondary">www.henrybarbara.com</a></div> -->
                            <div class="user-avatar-address">
                                <p class="border-bottom pb-3">
                                    <span class=" mb-2 d-xl-inline-block d-block ml-xl-4">
                                        系所
                                    </span>
                                    <span class=" mb-2 d-xl-inline-block d-block ml-xl-4">教師</span>
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
<!-- /influencer profile  -->
<!-- widgets   -->
<div class="row">
    <!-- total views   -->
    <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
        <div class="card">
            <div class="card-body">
                <div class="d-inline-block">
                    <h5 class="text-muted">總借用次數</h5>
                    <h2 class="mb-0">666,666</h2>
                </div>
                <div class="float-right icon-circle-medium  icon-box-lg  bg-info-light mt-1">
                    <i class="fa fa-eye fa-fw fa-sm text-info"></i>
                </div>
            </div>
        </div>
    </div>
    <!-- /total views   -->
    <!-- total followers   -->
    <div class="col-xl-3 col-lg-6 col-md-6 col-sm-12 col-12">
        <div class="card">
            <div class="card-body">
                <div class="d-inline-block">
                    <h5 class="text-muted">總借用時數</h5>
                    <h2 class="mb-0">12,345</h2>
                </div>
                <div class="float-right icon-circle-medium  icon-box-lg  bg-primary-light mt-1">
                    <i class="fa fa-user fa-fw fa-sm text-primary"></i>
                </div>
            </div>
        </div>
    </div>
    <!-- /total followers   -->
</div>
<!-- /widgets   -->
<div class="row">
    <!-- room log -->
    <div class="col-lg-12">
        <div class="section-block">
            <h3 class="section-title">借用紀錄</h3>
        </div>
        <div class="card">
            <form id="queryForm" class="needs-validation mx-4">
                <div class="form-group row">
                    <label for="RoomName" class="col-md-1 col-sm-1 col-xs-12 my-2">預約地點</label>
                    <div class="col-md-3 col-sm-3 col-xs-12 mb-3">
                        <select class="form-control" id="RoomName" name="RoomName" required="">
                            <optgroup label="RA-1">
                                <option>RA-101</option>
                                <option>RA-102</option>
                                <option>RA-103</option>
                                <option>RA-104</option>
                            </optgroup>
                            <optgroup label="RA-2">
                                <option>RA-201</option>
                                <option>RA-202</option>
                            </optgroup>
                        </select>
                    </div>
                    <label for="MeetingDate" class="col-md-1 col-sm-1 col-xs-12 my-2">預約日期</label>
                    <div class="col-md-3 col-sm-3 col-xs-12 mb-3">
                        <input type="date" class="form-control datetimepicker-input" id="MeetingDate" name="MeetingDate" required="" />
                    </div>
                    <div class="col-md-1 col-sm-1 col-xs-12">
                        <button type="button" class="btn btn-primary" onclick="GetObjList();">查詢</button>
                    </div>
                </div>
            </form>
        </div>
        <div class="card">
            <div class="campaign-table table-responsive">
                <table class="table">
                    <thead>
                        <tr class="border-0">
                            <th class="border-0">會議室名稱</th>
                            <th class="border-0">借用日期</th>
                            <th class="border-0">借用時段</th>
                            <th class="border-0">會議人數</th>
                            <th class="border-0">目的</th>
                            <th class="border-0">申請時間</th>
                            <th class="border-0">修改預約</th>
                            <th class="border-0">刪除預約</th>
                        </tr>
                    </thead>
                    <tbody class="objList"></tbody>                    
                </table>                
            </div>
        </div>
    </div>
    <!-- /room log -->
</div>
<!-- end content  -->

<div id="updateModal" class="modal fade" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div id="updateCard" class="modal-body card"></div>
        </div>
    </div>
</div>

@section scripts{
    <script>
        // 給input  date設定預設值
        var now = new Date();
        //格式化日，如果小於9，前面補0
        var day = ("0" + now.getDate()).slice(-2);
        //格式化月，如果小於9，前面補0
        var month = ("0" + (now.getMonth() + 1)).slice(-2);
        //拼裝完整日期格式
        var today = now.getFullYear() + "-" + (month) + "-" + (day);
        //完成賦值
        $('#MeetingDate').val(today);

        function Check(){
            console.log($("#updateForm").serialize());
            $("#updateModal").modal('hide');
        }

        //取得預約清單
        function GetObjList() {
            var formValues = $("#queryForm").serialize();

            $.ajax({
                url: '@Url.Action("ObjListPartialView", "RoomReservationLog")',
                data: formValues + "&StartTime=" + $('#MeetingDate').val(),
                type: 'post',
                success: function (data) {
                    $(".objList").html(data);
                },
                fail: function () {
                    alert("無預約!!");
                },
                error: function () {
                    alert("無預約!!");
                }
            });
        }

        //刪除預約確認
        function DeleteCheck(RoomName, StartTime, EndTime) {
            $.ajax({
                url: '@Url.Action("CheckObjExist", "RoomReservationLog")',
                data: "RoomName=" + RoomName + "&StartTime=" + StartTime + "&EndTime=" + EndTime,
                type: 'post',
                success: function (data) {
                    if (data) {
                        var confirmWord = "是否刪除 " + RoomName + " 預約?";
                        if (confirm(confirmWord)) {
                            DeleteObj(RoomName, StartTime, EndTime);
                        }
                    }
                    else {
                        alert("無法刪除該預約!!");
                    }
                },
                fail: function () {
                    alert("刪除預約錯誤!!");
                },
                error: function () {
                    alert("刪除預約錯誤!!");
                }
            });
            return false;
        }

        //刪除預約
        function DeleteObj(RoomName, StartTime, EndTime) {
            var confirmWord = "是否刪除 " + RoomName + " 預約?";
            var nowTime = new Date(); //當前時間

            if (!confirm(confirmWord)) {
                return false;
            }

            if(new Date(StartTime) <= nowTime || new Date(EndTime) <= nowTime)
            {
                alert("無法刪除過往預約!!");
                return false;
            }

            $.ajax({
                url: '@Url.Action("DeleteObj", "RoomReservationLog")',
                data: "RoomName=" + RoomName + "&StartTime=" + StartTime + "&EndTime=" + EndTime,
                type: 'post',
                success: function (data) {
                    if (data) {
                        GetObjList();
                        alert("刪除預約成功!!");
                    }
                    else {
                        alert("刪除預約失敗!!");
                    }
                },
                error: function () {
                    alert("刪除預約失敗!!");
                },
                fail: function () {
                    alert("刪除預約失敗!!");
                }
            });
        }

        //修改預約表單
        function GetUpdateObj(RoomName, StartTime, EndTime) {
            var nowTime = new Date(); //當前時間

            //if(new Date(StartTime) <= nowTime || new Date(EndTime) <= nowTime)
            //{
            //    alert("無法修改過往預約!!");
            //    return false;
            //}

            $.ajax({
                url: '@Url.Action("UpdateObjPartialView", "RoomReservationLog")',
                data: "RoomName=" + RoomName + "&StartTime=" + StartTime + "&EndTime=" + EndTime,
                type: 'post',
                success: function (data) {
                    if (data) {
                        $("#updateCard").html(data);
                        $('#updateModal').modal({
                            backdrop: 'static', keyboard: false
                        });
                    }
                    else {
                        alert("開啟修改預約視窗失敗!!");
                    }
                },
                error: function () {
                    alert("開啟修改預約視窗失敗!!");
                },
                fail: function () {
                    alert("開啟修改預約視窗失敗!!");
                }
            });
        }

        //預約明細
        function UpdateObj() {
            var formValues = $("#queryForm").serialize();
            var strDate = $('#MeetingDate').val();

            $.ajax({
                url: '@Url.Action("InsertObj", "RoomReservation")',
                data: formValues + '&StartTime=' + StartTime + '&EndTime=' + EndTime + '&ReservingPersonID=' + $("#NavUserID").val(),
                type: 'post',
                success: function (data) {
                    if (data) {
                        $("#updateModal").modal('hide');
                        alert("修改預約成功!!");
                    }
                    else {
                        alert("修改預約失敗!!");
                    }
                },
                error: function () {
                    alert("修改預約失敗!!");
                },
                fail: function () {
                    alert("修改預約失敗!!");
                }
            });
            return false;
        }
    </script>
}

Views/RoomReservationLog/ObjListPartialView.cshtml
@section styles{
}

@model IEnumerable<Meeting_room_dating.Reservation>
@foreach (var item in Model)
{
    <tr>
        <td>@item.RoomName</td>
        <td>@item.StartTime.Date</td>
        <td>@item.StartTime.ToShortTimeString() - @item.EndTime.ToShortTimeString()</td>
        <td>@item.PeopleNumber</td>
        <td>@item.Goal.Trim()</td>
        <td>@item.SubmitTime</td>
        <td>
            <button class="btn" onclick="GetUpdateObj('@item.RoomName','@item.StartTime.ToString("R")','@item.EndTime.ToString("R")')">
                修改
            </button>
        </td>
        <td>
            <button class="btn" onclick="DeleteObj('@item.RoomName','@item.StartTime.ToString("R")','@item.EndTime.ToString("R")')">
                刪除
            </button>
        </td>
    </tr>

}

@if (Model.Count() == 0)
{
<td id="alertWord" class="h3 my-4" style="color:red; text-align:center;" colspan="8">查無資料!</td>
}

@section scripts{
}

Views/RoomReservationLog/UpdateObjPartialView.cshtml
@model Meeting_room_dating.Reservation

<h5 class="card-header">修改預約</h5>
<div class="card-body">
    <form id="updateForm" class="needs-validation">
        <div class="mb-3 row">
            <div class="col-md-6 mb-3">
                <label for="RoomName">預約地點</label>
                <select class="form-control" id="RoomName" name="RoomName" text="@Model.RoomName" required="">
                    <optgroup label="RA-1">
                        <option>RA-101</option>
                        <option>RA-102</option>
                        <option>RA-103</option>
                        <option>RA-104</option>
                    </optgroup>
                    <optgroup label="RA-2">
                        <option>RA-201</option>
                        <option>RA-202</option>
                    </optgroup>
                </select>
            </div>
            <div class="col-md-6 mb-3">
                <label for="meetingDate">預約日期</label>
                <div class="form-group">
                    <input type="date" class="form-control datetimepicker-input" id="meetingDate" name="meetingDate" value="@Model.StartTime.ToString("d")" required="" />
                </div>
            </div>
        </div>
        <div class="mb-3 row">
            <div class="col-md-6 mb-3">
                <label for="startTime">開始時間</label>
                <div class="form-group">
                    <input type="time" class="form-control datetimepicker-input" id="startTime" name="startTime" value="@Model.StartTime.ToString("t")" required="" />
                </div>
            </div>
            <div class="col-md-6 mb-3">
                <label for="endTime">結束時間</label>
                <div class="form-group">
                    <input type="time" class="form-control datetimepicker-input" id="endTime" name="endTime" value="@Model.EndTime.ToString("t")" required="" />
                </div>
            </div>
        </div>
        <div class="mb-3">
            <label for="PeopleNumber">預計會議人數</label>
            <input type="number" class="form-control" id="PeopleNumber" name="PeopleNumber" value="@Model.PeopleNumber" required="" min="0" max="100" value="1">
            <div class="invalid-feedback">
                請輸入預計人數。
            </div>
        </div>
        <div class="mb-3">
            <label for="Goal">會議目的</label>
            <input type="text" class="form-control" id="Goal" name="Goal" value="@Model.Goal" placeholder="請輸入會議目的">
            <div class="invalid-feedback">
                請輸入會議目的。
            </div>
        </div>
        <hr class="mb-4">
        <button type="button" class="btn btn-primary btn-lg btn-block" onclick="Check();">修改</button>
    </form>
</div>